[metadata]
name = eman3
version = 0.1.0
description = EMAN3 - GPU-accelerated cryo-EM processing with NumPy and JAX
long_description = file: README.md
long_description_content_type = text/markdown
license_files = LICENSE

[options]
zip_safe = False
include_package_data = True
packages = find:
python_requires = >=3.10
install_requires =
	numpy
	jax
	jaxlib
	optax

[options.packages.find]
where = .
exclude =
	libEM.*

[options.entry_points]
console_scripts =
	# examples
	e3x_test_io = examples.e3x_test_io:main
	e3x_test_gui = examples.e3x_test_gui:main
	e3x_test_plot = examples.e3x_test_plot:main
	e3x_test_plot3d = examples.e3x_test_plot3d:main
	e3x_test_imagemx = examples.e3x_test_imagemx:main
	e3x_test_scene3d  = examples.e3x_test_scene3d:main
	# programs
	e3dpm_refine = programs.e3dpm_refine:main
	e3dpm = programs.e3dpm:main
	e3make3d_point = programs.e3make3d_point:main

